[BUG]: no found input "C:\path\to\your\file\Marvel_Tracker.py"

## Command Line
C:\Users\John\PycharmProjects\Authentication\.venv\Scripts\pyarmor gen -O dist_protected C:\\path\\to\\your\\file\\Marvel_Tracker.py

## Environments
Python 3.12.6
Pyarmor 9.0.7 (trial), 000000, non-profits
Platform windows.x86_64
Native windows.amd64
Home C:\Users\John\.pyarmor

